apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "example.fullname" . }}-secret"
  labels:
    {{- include "example.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.envvars.secretKey | b64enc }}